sudo: required
services:
    - docker

before_install:
    - docker build -t cech92/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true cech92/react-test npm test

after_success:
    # Build images
    - docker build -t cech92/multidocker-frontend ./frontend
    - docker build -t cech92/multidocker-nginx ./nginx
    - docker build -t cech92/multidocker-backend ./backend
    - docker build -t cech92/multidocker-worker ./worker
    # Login into docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push cech92/multidocker-frontend
    - docker push cech92/multidocker-nginx
    - docker push cech92/multidocker-backend
    - docker push cech92/multidocker-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-central-1
    app: multidocker
    env: Multidocker-env
    bucket_name: elasticbeanstalk-eu-central-1-371401786304
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY